"""track_config_oauth_events_refresh

Revision ID: 245d6ad9d0d3
Revises: b00cb40aabe3
Create Date: 2026-02-18 11:37:24.618193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245d6ad9d0d3'
down_revision: Union[str, None] = 'b00cb40aabe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_index(op.f('ix_oauth_accounts_id'), 'oauth_accounts', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('track_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('num_sectors', sa.Integer(), nullable=False),
    sa.Column('start_finish_lat', sa.Float(), nullable=True),
    sa.Column('start_finish_lon', sa.Float(), nullable=True),
    sa.Column('layout_data', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_configurations_id'), 'track_configurations', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('track_configuration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'active', 'completed', name='eventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['track_configuration_id'], ['track_configurations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    drivetrain_enum = sa.Enum('fwd', 'rwd', 'awd', name='drivetrain')
    drivetrain_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('cars', sa.Column('drivetrain', drivetrain_enum, nullable=True))
    op.add_column('cars', sa.Column('power_hp', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('weight_kg', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('engine_cc', sa.Integer(), nullable=True))
    op.alter_column('cars', 'notes',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.add_column('laps', sa.Column('gps_track', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('track_configuration_id', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('source_file_path', sa.String(length=512), nullable=True))
    op.add_column('sessions', sa.Column('app_source', sa.String(length=64), nullable=True))
    op.add_column('sessions', sa.Column('vehicle_hint', sa.String(length=128), nullable=True))
    op.drop_constraint('sessions_track_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'events', ['event_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'track_configurations', ['track_configuration_id'], ['id'])
    op.drop_column('sessions', 'track_id')
    op.drop_column('tracks', 'num_sectors')
    op.drop_column('tracks', 'length_meters')
    op.drop_column('tracks', 'layout_data')
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.add_column('tracks', sa.Column('layout_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('length_meters', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tracks', sa.Column('num_sectors', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('track_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_track_id_fkey', 'sessions', 'tracks', ['track_id'], ['id'])
    op.drop_column('sessions', 'vehicle_hint')
    op.drop_column('sessions', 'app_source')
    op.drop_column('sessions', 'source_file_path')
    op.drop_column('sessions', 'event_id')
    op.drop_column('sessions', 'track_configuration_id')
    op.drop_column('laps', 'gps_track')
    op.alter_column('cars', 'notes',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_column('cars', 'engine_cc')
    op.drop_column('cars', 'weight_kg')
    op.drop_column('cars', 'power_hp')
    op.drop_column('cars', 'drivetrain')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_track_configurations_id'), table_name='track_configurations')
    op.drop_table('track_configurations')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_oauth_accounts_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    # ### end Alembic commands ###
